
package org.reniec.rel;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SRELService", targetNamespace = "http://rel.reniec.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SRELService {


    /**
     * 
     * @param codigo
     * @param usuario
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSession", targetNamespace = "http://rel.reniec.org/", className = "org.reniec.rel.GetSession")
    @ResponseWrapper(localName = "getSessionResponse", targetNamespace = "http://rel.reniec.org/", className = "org.reniec.rel.GetSessionResponse")
    public String getSession(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "codigo", targetNamespace = "")
        String codigo);

    /**
     * 
     * @param nombres
     * @param apPaterno
     * @param usuario
     * @param apMaterno
     * @param sesion
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRegIdentAproximacion", targetNamespace = "http://rel.reniec.org/", className = "org.reniec.rel.GetRegIdentAproximacion")
    @ResponseWrapper(localName = "getRegIdentAproximacionResponse", targetNamespace = "http://rel.reniec.org/", className = "org.reniec.rel.GetRegIdentAproximacionResponse")
    public List<String> getRegIdentAproximacion(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "apPaterno", targetNamespace = "")
        String apPaterno,
        @WebParam(name = "apMaterno", targetNamespace = "")
        String apMaterno,
        @WebParam(name = "nombres", targetNamespace = "")
        String nombres);

    /**
     * 
     * @param codTxEmp
     * @param usuario
     * @param dniUserEmp
     * @param sesion
     * @param dni
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRegIdentConsolidada2", targetNamespace = "http://rel.reniec.org/", className = "org.reniec.rel.GetRegIdentConsolidada2")
    @ResponseWrapper(localName = "getRegIdentConsolidada2Response", targetNamespace = "http://rel.reniec.org/", className = "org.reniec.rel.GetRegIdentConsolidada2Response")
    public List<String> getRegIdentConsolidada2(
        @WebParam(name = "sesion", targetNamespace = "")
        String sesion,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "codTxEmp", targetNamespace = "")
        String codTxEmp,
        @WebParam(name = "dniUserEmp", targetNamespace = "")
        String dniUserEmp,
        @WebParam(name = "dni", targetNamespace = "")
        String dni);

}
