
package org.reniec.rel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SRELServiceService", targetNamespace = "http://rel.reniec.org/", wsdlLocation = "http://ws.reniec.gob.pe/SRELService/SRELServiceService?wsdl")
public class SRELServiceService
    extends Service
{

    private final static URL SRELSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SRELSERVICESERVICE_EXCEPTION;
    private final static QName SRELSERVICESERVICE_QNAME = new QName("http://rel.reniec.org/", "SRELServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ws.reniec.gob.pe/SRELService/SRELServiceService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SRELSERVICESERVICE_WSDL_LOCATION = url;
        SRELSERVICESERVICE_EXCEPTION = e;
    }

    public SRELServiceService() {
        super(__getWsdlLocation(), SRELSERVICESERVICE_QNAME);
    }

    public SRELServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SRELSERVICESERVICE_QNAME, features);
    }

    public SRELServiceService(URL wsdlLocation) {
        super(wsdlLocation, SRELSERVICESERVICE_QNAME);
    }

    public SRELServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SRELSERVICESERVICE_QNAME, features);
    }

    public SRELServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SRELServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SRELService
     */
    @WebEndpoint(name = "SRELServicePort")
    public SRELService getSRELServicePort() {
        return super.getPort(new QName("http://rel.reniec.org/", "SRELServicePort"), SRELService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SRELService
     */
    @WebEndpoint(name = "SRELServicePort")
    public SRELService getSRELServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rel.reniec.org/", "SRELServicePort"), SRELService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SRELSERVICESERVICE_EXCEPTION!= null) {
            throw SRELSERVICESERVICE_EXCEPTION;
        }
        return SRELSERVICESERVICE_WSDL_LOCATION;
    }

}
